### ISSUE TITLE
Moon (March) not work

### ISSUE THREAD

**Issue by Electric-Cat** [BananaPuncher714/LethalQuantities#60]
Well, I don’t know if this error occurred because of some conflict with other mods, but the “March” moon stops loading when the map’s Seed appears, not leaving this “Seed” screen and forcing to exit the game and re-enter.

Looking at the Moon configuration files I noticed that the “DungeonGeneration.cfg” file is the only one that has all dungeon generations as “0”. (where in others it is usually 300 in Level1Flow depending on the Moon)

There are other mods that influence dungeon generation but other Moons on my mod list have the same influence and do not freeze when generating the map, besides even changing the “0” values to any other value does not help and continues to freeze on the Moon loading.

I have the Error log that I will send below and as I said, it may be a conflict with other mods but as it was the only moon (already existing in the game) that gave an error I thought it best to send a warning here.

(There was another Moon that gave an error but this Moon was from a mod, but had exactly the same problem of having “0” in all dungeon values)

```
[Error  : Unity Log] KeyNotFoundException: The given key 'Level1Flow3Exits' was not present in the dictionary.
Stack trace:
System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) (at <787acc3c9a4c471ba7d971300105af24>:IL_001E)
LethalQuantities.Patches.RoundManagerPatch.onGenerateNewFloorPrefix (RoundManager __instance) (at <7c64dbe991c44b6ebae23a78ed2efeb9>:IL_00AD)
(wrapper dynamic-method) RoundManager.DMD<RoundManager::GenerateNewFloor>(RoundManager)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Trampoline<RoundManager::GenerateNewFloor>?-1567772652(RoundManager)
LethalLevelLoader.Patches.Dungeon_GenerateNewFloor_Prefix (On.RoundManager+orig_GenerateNewFloor orig, RoundManager self) (at <519c156a8dbc4475bcf45d93d9f3cd0d>:IL_000C)
(wrapper dynamic-method) LethalLib.Modules.Dungeon.DMD<LethalLib.Modules.Dungeon::RoundManager_GenerateNewFloor>(On.RoundManager/orig_GenerateNewFloor,RoundManager)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<RoundManager::GenerateNewFloor>?-125521540(RoundManager)
LethalLevelLoader.LethalLevelLoaderNetworkManager.SetRandomExtendedDungeonFlowClientRpc (System.Int32[] dungeonFlowIDs, System.Int32[] rarities) (at <519c156a8dbc4475bcf45d93d9f3cd0d>:IL_01CE)
LethalLevelLoader.LethalLevelLoaderNetworkManager.GetRandomExtendedDungeonFlowServerRpc () (at <519c156a8dbc4475bcf45d93d9f3cd0d>:IL_01D4)
LethalLevelLoader.LethalLevelLoaderNetworkManager.__rpc_handler_12573863 (Unity.Netcode.NetworkBehaviour target, Unity.Netcode.FastBufferReader reader, Unity.Netcode.__RpcParams rpcParams) (at <519c156a8dbc4475bcf45d93d9f3cd0d>:IL_007B)
Unity.Netcode.RpcMessageHelpers.Handle (Unity.Netcode.NetworkContext& context, Unity.Netcode.RpcMetadata& metadata, Unity.Netcode.FastBufferReader& payload, Unity.Netcode.__RpcParams& rpcParams) (at <895801699cfc4b4ab52267f31e2a4998>:IL_004E)
Rethrow as Exception: Unhandled RPC exception!
UnityEngine.Debug:LogException(Exception)
Unity.Netcode.RpcMessageHelpers:Handle(NetworkContext&, RpcMetadata&, FastBufferReader&, __RpcParams&)
Unity.Netcode.ServerRpcMessage:Handle(NetworkContext&)
Unity.Netcode.NetworkBehaviour:__endSendServerRpc(FastBufferWriter&, UInt32, ServerRpcParams, RpcDelivery)
LethalLevelLoader.LethalLevelLoaderNetworkManager:GetRandomExtendedDungeonFlowServerRpc()
LethalLevelLoader.DungeonLoader:SelectDungeon()
LethalLevelLoader.Patches:InjectHostDungeonFlowSelection()
RoundManager:DMD<RoundManager::GenerateNewLevelClientRpc>(RoundManager, Int32, Int32)
RoundManager:__rpc_handler_1193916134(NetworkBehaviour, FastBufferReader, __RpcParams)
Unity.Netcode.RpcMessageHelpers:Handle(NetworkContext&, RpcMetadata&, FastBufferReader&, __RpcParams&)
Unity.Netcode.ClientRpcMessage:Handle(NetworkContext&)
Unity.Netcode.NetworkBehaviour:__endSendClientRpc(FastBufferWriter&, UInt32, ClientRpcParams, RpcDelivery)
RoundManager:DMD<RoundManager::GenerateNewLevelClientRpc>(RoundManager, Int32, Int32)
<LoadNewLevelWait>d__115:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
```

> "stops loading when the map’s Seed appears"

![imagem_2024-02-17_224805868](https://github.com/BananaPuncher714/LethalQuantities/assets/60434386/c055ace8-f3b6-402e-9172-c072049b3271)

**Comment by BananaPuncher714** [comment]
Thanks, I'll have to take a look at this. Does the error occur if you set any of the dungeon flow rarities to a non-zero value?

**Comment by BananaPuncher714** [comment]
After some testing, it seems that March in particular does not have any dungeon flows set by default(where all rarities are 0), which is probably due to how it has 3 fire exits. The game does something that I'm not too sure about in order to set the dungeon, so it might not be possible to change the flows via LethalQuantities by default.

However, if you are using LethalLevelLoader, it should work fine, since they patch the fire exits for all dungeons. For the error, I will post an update which should fix the problem.

**Comment by Electric-Cat** [comment]
> Thanks, I'll have to take a look at this. Does the error occur if you set any of the dungeon flow rarities to a non-zero value?

Yes, even changing the values to anything other than 0, the same error continues to occur. 

> After some testing, it seems that March in particular does not have any dungeon flows set by default(where all rarities are 0), which is probably due to how it has 3 fire exits. The game does something that I'm not too sure about in order to set the dungeon, so it might not be possible to change the flows via LethalQuantities by default.
> 
> However, if you are using LethalLevelLoader, it should work fine, since they patch the fire exits for all dungeons. For the error, I will post an update which should fix the problem.

I already have LethalLevelLoader in the mod list, but it didn’t fix the error. The other mod I mentioned that has exactly the same error would be [Outpost 31](https://thunderstore.io/c/lethal-company/p/LethalMatt/Outpost_31/).

It would be nice to add a new option for the moons that allows hiding certain moons, in case of bugs or even for personal preference. Example: “I’m going to download only SCP mods, I’m going to hide the primary moons and just leave SCP themed ones.”

**Comment by Electric-Cat** [comment]
March now works, but unfortunately the outpost 31 mod does not, but I believe it is no longer an error of LethalQuantities, but anyway I will send the error log.

But anyway, thank you for listening to me! Keep up the good work and may everything go well with you/you all <3

```
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
HDLethalCompany.Patch.GraphicsPatch.SetFogQuality () (at <af4549f5e2244be2adf4eeb0cf8c6293>:IL_003D)
HDLethalCompany.Patch.GraphicsPatch.RoundPostFix () (at <af4549f5e2244be2adf4eeb0cf8c6293>:IL_0001)
(wrapper dynamic-method) RoundManager.DMD<RoundManager::GenerateNewFloor>(RoundManager)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Trampoline<RoundManager::GenerateNewFloor>?-322805822(RoundManager)
LethalLevelLoader.Patches.Dungeon_GenerateNewFloor_Prefix (On.RoundManager+orig_GenerateNewFloor orig, RoundManager self) (at <519c156a8dbc4475bcf45d93d9f3cd0d>:IL_000C)
(wrapper dynamic-method) LethalLib.Modules.Dungeon.DMD<LethalLib.Modules.Dungeon::RoundManager_GenerateNewFloor>(On.RoundManager/orig_GenerateNewFloor,RoundManager)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<RoundManager::GenerateNewFloor>?-70336700(RoundManager)
LethalLevelLoader.LethalLevelLoaderNetworkManager.SetRandomExtendedDungeonFlowClientRpc (System.Int32[] dungeonFlowIDs, System.Int32[] rarities) (at <519c156a8dbc4475bcf45d93d9f3cd0d>:IL_01CE)
LethalLevelLoader.LethalLevelLoaderNetworkManager.__rpc_handler_1934987400 (Unity.Netcode.NetworkBehaviour target, Unity.Netcode.FastBufferReader reader, Unity.Netcode.__RpcParams rpcParams) (at <519c156a8dbc4475bcf45d93d9f3cd0d>:IL_00B8)
Unity.Netcode.RpcMessageHelpers.Handle (Unity.Netcode.NetworkContext& context, Unity.Netcode.RpcMetadata& metadata, Unity.Netcode.FastBufferReader& payload, Unity.Netcode.__RpcParams& rpcParams) (at <895801699cfc4b4ab52267f31e2a4998>:IL_004E)
Rethrow as Exception: Unhandled RPC exception!
UnityEngine.Debug:LogException(Exception)
Unity.Netcode.RpcMessageHelpers:Handle(NetworkContext&, RpcMetadata&, FastBufferReader&, __RpcParams&)
Unity.Netcode.ClientRpcMessage:Handle(NetworkContext&)
Unity.Netcode.NetworkBehaviour:__endSendClientRpc(FastBufferWriter&, UInt32, ClientRpcParams, RpcDelivery)
LethalLevelLoader.LethalLevelLoaderNetworkManager:SetRandomExtendedDungeonFlowClientRpc(Int32[], Int32[])
LethalLevelLoader.LethalLevelLoaderNetworkManager:GetRandomExtendedDungeonFlowServerRpc()
LethalLevelLoader.LethalLevelLoaderNetworkManager:__rpc_handler_12573863(NetworkBehaviour, FastBufferReader, __RpcParams)
Unity.Netcode.RpcMessageHelpers:Handle(NetworkContext&, RpcMetadata&, FastBufferReader&, __RpcParams&)
Unity.Netcode.ServerRpcMessage:Handle(NetworkContext&)
Unity.Netcode.NetworkBehaviour:__endSendServerRpc(FastBufferWriter&, UInt32, ServerRpcParams, RpcDelivery)
LethalLevelLoader.LethalLevelLoaderNetworkManager:GetRandomExtendedDungeonFlowServerRpc()
LethalLevelLoader.DungeonLoader:SelectDungeon()
LethalLevelLoader.Patches:InjectHostDungeonFlowSelection()
RoundManager:DMD<RoundManager::GenerateNewLevelClientRpc>(RoundManager, Int32, Int32)
RoundManager:__rpc_handler_1193916134(NetworkBehaviour, FastBufferReader, __RpcParams)
Unity.Netcode.RpcMessageHelpers:Handle(NetworkContext&, RpcMetadata&, FastBufferReader&, __RpcParams&)
Unity.Netcode.ClientRpcMessage:Handle(NetworkContext&)
Unity.Netcode.NetworkBehaviour:__endSendClientRpc(FastBufferWriter&, UInt32, ClientRpcParams, RpcDelivery)
RoundManager:DMD<RoundManager::GenerateNewLevelClientRpc>(RoundManager, Int32, Int32)
<LoadNewLevelWait>d__115:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
```

**Comment by BananaPuncher714** [comment]
I did some more testing with this profile: `018dc2b9-7632-7483-c6c1-a0d7a67a12ea` and both March and Outpost 31 work without error, so it seems to be some other mod that is causing the errors. I set all moons to only use Level2Flow, in the global dungeon generation config.

As for hiding moons, if you mean in the config, there's not really any alternative except for not enabling the configs for certain moons. The terminal list is something that I don't touch, and don't really want to, especially with so many other mods changing how the moons command functions.

**Comment by Electric-Cat** [comment]
Sorry, I was configuring so many files that I ended up confusing the mods. The mod that allows you to view the moons in the terminal and change their order (difficulty, price, etc) is the LethalLevelLoader.

And in the case of the Outpost 31 mod, there must be some mod that is really affecting it, but I find it strange that it is only this specific moon, since I have the SCP moon as another pack of about 7 moons that none represent this type of errors, but I’ll look into this later, thank you anyway <3
